# Generated by Django 3.2.13 on 2022-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactListApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
