# Generated by Django 3.2.13 on 2022-05-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactListApi', '0002_auto_20220501_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(max_length=10),
        ),
    ]
