# Generated by Django 3.2.13 on 2022-05-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactListApi', '0003_auto_20220501_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
