# Generated by Django 3.2.13 on 2022-05-10 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactListLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
                ('type', models.CharField(max_length=10)),
                ('last_updated_on', models.DateTimeField(default=datetime.datetime(2022, 5, 10, 7, 15, 10, 585976))),
                ('creator', models.CharField(max_length=10)),
                ('folder', models.CharField(max_length=10)),
                ('used_in', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
