# Generated by Django 3.2.13 on 2022-05-10 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlistlibrary',
            name='creator',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contactlistlibrary',
            name='folder',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contactlistlibrary',
            name='last_updated_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 7, 20, 17, 201467)),
        ),
        migrations.AlterField(
            model_name='contactlistlibrary',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
