# Generated by Django 3.2.13 on 2022-05-10 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactLibrary', '0002_auto_20220510_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlistlibrary',
            name='creator',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactlistlibrary',
            name='folder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactlistlibrary',
            name='last_updated_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 7, 22, 56, 119154)),
        ),
        migrations.AlterField(
            model_name='contactlistlibrary',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactlistlibrary',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
